;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; │░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; main colors
background = #FF000000
foreground = #FFFFFFFF
sep = #FFFFFFFF
track = #33FFFFFF

white = #FFFFFFFF
black = #000000
red = #FFFFFFFF
pink = #FFFFFFFF
purple = #FFFFFFFF
blue = #FFFFFFFF
cyan = #FFFFFFFF
teal = #FFFFFFFF
green = #FFFFFFFF
lime = #FFFFFFFF
yellow = #FFFFFFFF
amber = #FFFFFFFF
orange = #FFFFFFFF
brown = #FFFFFFFF
indigo = #FFFFFFFF
gray = #FFFFFFFF
blue-gray = #FFFFFFFF

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
