conky.config = {
  alignment = 'top_left',
  background = false,
  cpu_avg_samples = 2,
  default_color = 'ffffff',
  double_buffer = true,
  draw_borders = false,
  draw_outline = false,
  draw_shades = false,
  extra_newline = false,
  gap_x = 35,
  gap_y = 67,
  minimum_width = 396,
  minimum_height = 483,
  net_avg_samples = 2,
  no_buffers = true,
  out_to_console = false,
  out_to_x = true,
  own_window = true,
  own_window_type = 'override',
  own_window_class = 'conky',
  own_window_title = 'mimosa-widget',
  own_window_argb_visual = true,
  own_window_argb_value = 255,
  own_window_transparent = true,
  own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
  show_graph_scale = false,
  total_run_times = 0,
  update_interval = 5,
  lua_load = '/home/davi/.config/conky/Mimosa/widget.lua',
  lua_draw_hook_post = 'widget_draw',
};

conky.text = [[ ]];
